<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <!-- Sprint 10.30: 抑制 nullable 引用警告 -->
    <NoWarn>CS8600;CS8602;CS8604;CS8625;CS8629;CS8632</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FreeSql" Version="3.5.310" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>

</Project>
